---
title: "Junk and Notes"
author: "Rachel Ledig"
date: "12/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Now that this is useless. 
```{r}

results <- "/Volumes/RachelExternal/Thesis/Thesis/Plots/IrrFrac/"  

irrfrac.graph <- function(df, na.rm = TRUE, ...){
  
  # create list of counties in data to loop over 
  yearlist <- unique(df$year)
  
  # create for loop to produce ggplot2 graphs 
  for (i in seq_along(yearlist)) { 
    
    # create plot for each county in df
    
      irrfrac <- ggplot(data = world) +
        geom_sf() +
        xlab("Longitude") + ylab("Latitude") +
        ggtitle("World map") +
        geom_tile(data = subset(df, df$year==yearlist[i]), aes(lon, lat, fill = measurement)) + 
         scale_fill_viridis_c(direction = -1, limits = c(0,1)) + 
        labs(fill = "Irr. Fraction") +
        ggtitle(paste(yearlist[i], "Irrigation Fraction"))
      
  
    # save plots as .pdf
    ggsave(irrfrac, file=paste(results, paste0(yearlist[i],"irrfract",".jpeg")), scale= 5, dpi = 500)
    
    # print plots to screen
    print(irrfrac)
  }
}

# run graphing function on long df
irrfrac.graph(irrfrac_long)
```


```{r}
irrfrac <- ggplot(data = world2) +
        geom_sf() +
        xlab("Longitude") + ylab("Latitude") +
        ggtitle("World map") +
        geom_tile(data = subset(irrfrac_sub), aes(lon, lat, fill = measurement)) + 
        scale_fill_viridis_c(direction = -1, limits = c(0,1)) + 
        labs(fill = "Irr. Fraction") + ggtitle("Irrigation Fraction")

irrfrac
      
  
    # save plots as .pdf
    ggsave(irrfrac, file=paste(results, "irrfrac", ".jpeg", sep=''), scale= 5, dpi = 500)
    
```