---
title: "FFS"
output: html_notebook
---

```{r}
library(tidyverse)
library(gganimate)
library(wbstats)
library(viridis)
library(ggplot2)

```

```{r}
ISO <- subset(countrystats, select = c("ISO", "countryname"))
ISO <- ISO %>% mutate(counrtyname = str_re)
```

```{r}
ag <- read.csv("/Volumes/RachelExternal/Thesis/Thesis/DataWesternosprey/agriculture_percent_of_gdp.csv")
income <- read.csv("/Volumes/RachelExternal/Thesis/Thesis/DataWesternosprey/income_per_person_gdppercapita_ppp_inflation_adjusted.csv")
gdptot <- read.csv("/Volumes/RachelExternal/Thesis/Thesis/DataWesternosprey/total_gdp_us_inflation_adjusted.csv")
```

```{r}
str(ag)
colnames(ag) <- c("countryname","1960":"2019")
ag <- ag %>% pivot_longer(!countryname, names_to = "year", values_to = "agperc")
ag <- ag %>% subset(year  <= 2005)
ag <- ag %>%
  mutate(countryname = str_replace_all(countryname, " ", "_")) 
ag <- merge(ag, ISO, on = "countryname", all.x = TRUE)

ag %>% 
  group_by(countryname) %>% 
  select(everything()) %>%  # replace to your needs
  summarise_all(funs(sum(is.na(.))))



view(ag)

```

```{r}
str(income)
colnames(income) <- c("country","1800":"2040")
income <- income %>% pivot_longer(!country, names_to = "year", values_to = "income")
income <- income %>% subset(year >= 1960 & year <= 2005)
income %>%
    mutate(country = str_replace(country, " ", "_"))
```

```{r}
str(gdptot)
colnames(gdptot) <- c("country","1960":"2019")
gdptot <- gdptot %>% pivot_longer(!country, names_to = "year", values_to = "totalgdp")
gdptot <- gdptot %>% subset(year  <= 2005)
gdptot %>%
    mutate(country = str_replace(country, " ", "_"))
```

```{r}
grouped_gghistostats(
  data = dplyr::filter(
    .data = d,
    countryname %in% c("Russia", "Bangladesh", "Italy", "India")
  ),
  x = Frac,
  test.value = 0.002,
  type = "bayesian",
  xlab = "Irrigation Fraction",
  grouping.var = countryname)

```

```{r}
# libraries needed

library(tidyverse)
library(ggplot2)
library(viridis)
library(gganimate)
library(wbstats)

# rosling chart in one command

# pull the country data down from the World Bank - three indicators
wbstats::wb(indicator = c("SP.DYN.LE00.IN", "NY.GDP.PCAP.CD", "SP.POP.TOTL"), 
                       country = "countries_only", startdate = 1960, enddate = 2018)  %>% 
  # pull down mapping of countries to regions and join
  dplyr::left_join(wbstats::wbcountries() %>% 
                     dplyr::select(iso3c, region)) %>% 
  # spread the three indicators
  tidyr::pivot_wider(id_cols = c("date", "country", "region"), names_from = indicator, values_from = value) %>% 
  # plot the data
  ggplot2::ggplot(aes(x = log(`GDP per capita (current US$)`), y = `Life expectancy at birth, total (years)`,
                      size = `Population, total`)) +
  ggplot2::geom_point(alpha = 0.5, aes(color = region)) +
  ggplot2::scale_size(range = c(.1, 16), guide = FALSE) +
  ggplot2::scale_x_continuous(limits = c(2.5, 12.5)) +
  ggplot2::scale_y_continuous(limits = c(30, 90)) +
  viridis::scale_color_viridis(discrete = TRUE, name = "Region", option = "viridis") +
  ggplot2::labs(x = "Log GDP per capita",
                y = "Life expectancy at birth") +
  ggplot2::theme_classic() +
  ggplot2::geom_text(aes(x = 7.5, y = 60, label = date), size = 14, color = 'lightgrey', family = 'Oswald') +
  # animate it over years
  gganimate::transition_states(date, transition_length = 1, state_length = 1) +
  gganimate::ease_aes('cubic-in-out')
  

```

```{r}
econ <- wb(
  indicator = c("NY.GDP.PCAP.CD", "SP.POP.TOTL"),                         
  country = "countries_only", 
  startdate = 1960, 
  enddate = 2005
) %>%
  left_join(wbcountries() %>% 
              select(iso3c, region)) %>%
  pivot_wider(
    id_cols = c("date", "country", "region", "iso3c"), 
    names_from = indicator, 
    values_from = value
    ) %>% 
  rename( ISO = iso3c, year = date) 
econ$year <- as.numeric(econ$year)
econ$ISO <- as.factor(econ$ISO)

join <- 
  econ %>% 
  right_join(y = subset(countrystats, year >= 1960), by = c("ISO", "year"))

join %>% 
  ggplot2::ggplot(aes(x = log(`GDP per capita (current US$)`), 
                    y = `IrrFrac`,                          
                    size = `Population, total`,
                    color = region)) +  
  ggplot2::geom_point(alpha = 0.5) +  
  ggplot2::scale_size(range = c(.1, 16), guide = FALSE) +    
  ggplot2::scale_x_continuous(limits = c(2.5, 12.5)) +  
  ggplot2::scale_y_continuous(limits = c(0, 0.4)) + 
  viridis::scale_color_viridis(
    discrete = TRUE, name = "Region", option = "viridis") + 
  ggplot2::labs(x = "Log GDP per capita",                
                y = "% of Total Area Irrigated") + 
  ggplot2::theme_classic() +  
  ggplot2::geom_text(aes(x = 7.5, y = 60, label = year), 
                     size = 14, color = 'lightgrey') + 
  gganimate::transition_states(year, transition_length = 1, state_length = 1) +
  gganimate::ease_aes('cubic-in-out')

```

```{r}
tenyear <- read.csv2("/Volumes/RachelExternal/Thesis/Data/SiebertData/HID_v10/Country_tenyear_ha.csv")
tenyear <- as.data.frame(tenyear)
```


