---
title: "README" 
output: html_notebook
---

# Variables in Country Level Model
ISO   
year 
country   
ID      
aei_ha    
yearcount   
area_km      
irrperc       
irrfrac        
four_regions     
eight_regions      
six_regions       
Latitude          
Longitude         
World.bank.region    
population           
log_pop      
log_pop_std      
income           
log_income        
log_income_std     
preciptot         
precip_sc         
precip_std         
log_precip       
log_precip_sc    
log_precip_std    
cellaream2        
Temperate_cereals    
Rice               
Maize                
Tropical_cereals     
Pulses               
Temperate_roots      
Tropical_roots       
Sunflower            
Soybean           
Groundnuts          
Rapeseed             
Sugarcane            
Others              
Managed_Grasslands  
Bio.energy_Grass     
Bio.energy_Tree      
Temperate_cereals.1  
Rice.1               
Maize.1              
Tropical_cereals.1   
Pulses.1             
Temperate_roots.1    
Tropical_roots.1     
Sunflower.1          
Soybean.1            
Groundnuts.1         
Rapeseed.1           
Sugarcane.1          
Others.1             
Managed_Grasslands.1 
Bio.energy_Grass.1    
Bio.energy_Tree.1    
rugged               
rugged_sc  