---
title: "Models"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(brms)
library(rstan)
library(dplyr)
```

```{r}
#lets sample to see if we can induce some reaction from the model.
fit1sub <- d %>% subset(year == "2005" & Frac > 0.1) %>% sample_n(1000, na.rm = TRUE)
# make log version of outcome 

# extract countries with GDP data
#dd <- d[ complete.cases(d$GDP) , ]

fit1sub$log_gdp <- log( fit1sub$GDP )
# rescale variables
#i think i have to standardize the predictor variable.. its all bunched up around 0
fit1sub$log_gdp_std <- fit1sub$GDP / mean(fit1sub$GDP) 

fit1sub$popdens_std <- fit1sub$popdens / mean(fit1sub$popdens)
fit1sub$precipmm_std <- fit1sub$precipmm / mean(fit1sub$precipmm)
fit1sub$fracperc <-fit1sub$Frac *100
fit1sub$latabs <- abs(fit1sub$lat)/max(abs(fit1sub$lat))
summary(fit1sub)
```

```{r}
set.seed(1000)
fit1 <- brm(data = fit1sub, 
      family = hurdle_gamma(),
      bf(Frac ~  1 + log_gdp_std + precipmm_std),
      iter = 4000, warmup = 2000, 
      control = list(adapt_delta = 0.9))
```
uuuufff this takes a long time to fit... 
```{r}
summary(fit1)
```
```{r}
plot(conditional_effects(fit1))
```

```{r}
mcmc_plot(fit1)
```

```{r}
set.seed(1000)
fit2 <- brm(data = fit1sub, 
      family = hurdle_lognormal(),
      bf(Frac ~  1 + log_gdp_std + precipmm_std),
      iter = 4000, warmup = 2000, 
      control = list(adapt_delta = 0.9))
```

```{r}
summary(fit2)
pp_check(fit2)
pp_check(fit1)
```

## Let's keep simplifiying this
```{r}
#I need to put an id col in d.... 
d$id <- as.factor(rep(1:67420, 105))

fit2sub <- d %>% subset(year == "1960" |year == "2005") %>% subset(countryname == "Bangladesh" | countryname == "United_Kingdom")


fit2sub$log_gdp <- log( fit2sub$GDP )
# rescale variables
#i think i have to standardize the predictor variable.. its all bunched up around 0
fit2sub$log_gdp_std <- fit2sub$GDP / mean(fit2sub$GDP) 

fit2sub$popdens_std <- fit2sub$popdens / mean(fit2sub$popdens)
fit2sub$precipmm_std <- fit2sub$precipmm / mean(fit2sub$precipmm)
fit2sub$fracperc <-fit2sub$Frac *100
fit2sub$latabs <- abs(fit2sub$lat)/max(abs(fit2sub$lat))
summary(fit2sub)
```

ok we got an id column. lets construct perhaps a varying intercept model. 
```{r}
set.seed(1000)
fit3 <- brm(data = fit2sub, 
      family = hurdle_lognormal(),
      bf(Frac ~  1 + log_gdp_std + precipmm_std),
      iter = 4000, warmup = 2000, 
      control = list(adapt_delta = 0.9))
```

```{r}
summary(fit3)
pp_check(fit3)
```

```{r}
set.seed(1000)
fit4 <- brm(data = fit2sub, 
      family = hurdle_gamma(),
      bf(Frac ~  1 + log_gdp_std + precipmm_std + (1|year), hu ~  1 + log_gdp_std + precipmm_std + (1|year)),
      iter = 4000, warmup = 2000, 
      control = list(adapt_delta = 0.9))
```
that took a long time to run.
```{r}
summary(fit4)
pp_check(fit4)
```
```{r}
mcmc_plot(fit4)
```

```{r}

pp_check(fit4)
plot(conditional_effects(fit4))
```

