```{r setup}
library(tidyverse)
library(tidybayes)
library(brms)


#
# This sets a global theme for all my plots. 
theme_set(theme_minimal() +
            theme(
              plot.background = element_blank()
              ,panel.grid.major = element_blank()
              ,panel.background = element_blank()
              ,axis.text.x  = element_text(angle=90, vjust=0.5, size=8)
            ))

model = `165aa_5yronlyISO_notimeserieszi`
data = aei_nocrop_samp165aa_5yr
```


```{r checks}
### Model summary at the 50% uncertainity interval
# Group summary and population level estimates
summary(`165aa_5yronlyISO_notimeserieszi`, prob = 0.5)

#fixed effects
fixef <- as.data.frame(fixef(`165aa_5yronlyISO_notimeserieszi`, groups="ISO", probs = 0.5)) %>% exp()

#random effects
ranef <- as.data.frame(ranef(`165aa_5yronlyISO_notimeserieszi`, groups="ISO", probs = 0.5))%>% exp()

#combined
coefs <- as.data.frame(coef(`165aa_5yronlyISO_notimeserieszi`, groups="ISO", probs = 0.5)) %>% inv_logit_scaled()

### Model checking plots. Posterior predict. 
pp_check(`165aa_5yronlyISO_notimeserieszi`, ndraws = 100)

###
pp_check(composite_ISO, type = "ecdf_overlay", ndraws = 100)

```

```{r}
posterior_samples(model, pars = "b_") %>% 
  mutate(across(.cols = starts_with("b_phi"), exp)) %>% 
  mutate(across(.cols = c(- starts_with("b_phi")), plogis)) %>% 
  posterior_summary() %>% 
  as.data.frame() %>% 
  rownames_to_column("Parameter")
```

```{r}
coef(`165aa_5yronlyISO_notimeserieszi`, robust = T)$ISO[, , ] %>% 
  as_tibble() %>%
  mutate(post_mdn = inv_logit_scaled(everything()))
```



# Regional Country level plots mu

```{r condeffs_mu}

cond_notimeserieszi_mu_precip <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_mu$`yearcount:precip`, ., by = "ISO")

cond_notimeserieszi_mu_rugged <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_mu$`yearcount:rugged`, ., by = "ISO")

cond_notimeserieszi_mu_gdppc <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_mu$`yearcount:gdppc`, ., by = "ISO")

cond_notimeserieszi_mu_popdens <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_mu$`yearcount:popdens`, ., by = "ISO")

cond_notimeserieszi_mu_ddregime <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_mu$`yearcount:DD.regime`, ., by = "ISO")



cond_notimeserieszi_mu_precip_only <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_mu$precip, ., by = "ISO")

cond_notimeserieszi_mu_rugged_only <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_mu$rugged, ., by = "ISO")

cond_notimeserieszi_mu_gdppc_only <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_mu$gdppc, ., by = "ISO")

cond_notimeserieszi_mu_popdens_only <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_mu$popdens, ., by = "ISO")

cond_notimeserieszi_mu_ddregime_only <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_mu$DD.regime, ., by = "ISO")


```

#interactions

```{r condeffs_mu_plots_precip}

cond_notimeserieszi_mu_precip %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_precip %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_precip %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_precip %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_precip %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_precip %>% 
  subset(eight_regions == "africa_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_precip %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_precip %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```

```{r condeffs_mu_plots_rugged}

cond_notimeserieszi_mu_rugged %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_rugged %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_rugged %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_rugged %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_rugged %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_rugged %>% 
  subset(eight_regions == "africa_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_rugged %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_rugged %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```

```{r condeffs_mu_plots_gdppc}

cond_notimeserieszi_mu_gdppc %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_gdppc %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_gdppc %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_gdppc %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_gdppc %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_gdppc %>% 
  subset(eight_regions == "africa_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_gdppc %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_gdppc %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```

```{r condeffs_mu_plots_popdens}

cond_notimeserieszi_mu_popdens %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_popdens %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_popdens %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_popdens %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_popdens %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_popdens %>% 
  subset(eight_regions == "africa_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_popdens %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_popdens %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```

```{r condeffs_mu_plots_ddregime}

cond_notimeserieszi_mu_ddregime %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_ddregime %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_ddregime %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_ddregime %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_ddregime %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_ddregime %>% 
  subset(eight_regions == "africa_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_ddregime %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_mu_ddregime %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__, group = effect2__, color = effect2__, fill = effect2__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__, group = effect2__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```

#individual predictors


```{r condeffs_mu_plots_precip}

cond_notimeserieszi_mu_precip_only %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_precip_only %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_precip_only %>% 
  subset(eight_regions == "america_north") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_precip_only %>% 
  subset(eight_regions == "america_south") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_precip_only %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_precip_only %>% 
  subset(eight_regions == "africa_north") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_precip_only %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_precip_only %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)


```

```{r condeffs_mu_plots_rugged}

cond_notimeserieszi_mu_rugged_only %>% 
  subset(eight_regions == "asia_west") %>% 
   ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_rugged_only %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_rugged_only %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_rugged_only %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_rugged_only %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_rugged_only %>% 
  subset(eight_regions == "africa_north") %>% 
   ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_rugged_only %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_rugged_only %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```

```{r condeffs_mu_plots_gdppc}

cond_notimeserieszi_mu_gdppc_only %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_gdppc_only %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_gdppc_only %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_gdppc_only %>% 
  subset(eight_regions == "america_south") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_gdppc_only %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_gdppc_only %>% 
  subset(eight_regions == "africa_north") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_gdppc_only %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_gdppc_only %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)



```

```{r condeffs_mu_plots_popdens}

cond_notimeserieszi_mu_popdens_only %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_popdens_only %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_popdens_only %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_popdens_only %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_popdens_only %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_popdens_only %>% 
  subset(eight_regions == "africa_north") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_popdens_only %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_popdens_only %>% 
  subset(eight_regions == "europe_west") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3, color = NA) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3)


```

```{r condeffs_mu_plots_ddregime}

cond_notimeserieszi_mu_ddregime_only %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_errorbar(aes(y=estimate__, ymin = lower__, ymax = upper__,x= effect1__, group = effect1__)) +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_ddregime_only %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_errorbar(aes(y=estimate__, ymin = lower__, ymax = upper__,x= effect1__, group = effect1__)) +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_ddregime_only %>% 
  subset(eight_regions == "america_north") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_errorbar(aes(y=estimate__, ymin = lower__, ymax = upper__,x= effect1__, group = effect1__)) +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_ddregime_only %>% 
  subset(eight_regions == "america_south") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_errorbar(aes(y=estimate__, ymin = lower__, ymax = upper__,x= effect1__, group = effect1__)) +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_ddregime_only %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
ggplot(aes(x=effect1__, y=estimate__)) +
  geom_errorbar(aes(y=estimate__, ymin = lower__, ymax = upper__,x= effect1__, group = effect1__)) +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_ddregime_only %>% 
  subset(eight_regions == "africa_north") %>% 
ggplot(aes(x=effect1__, y=estimate__)) +
  geom_errorbar(aes(y=estimate__, ymin = lower__, ymax = upper__,x= effect1__, group = effect1__)) +
  facet_wrap(~Countryname, ncol = 3)


cond_notimeserieszi_mu_ddregime_only %>% 
  subset(eight_regions == "europe_east") %>% 
ggplot(aes(x=effect1__, y=estimate__)) +
  geom_errorbar(aes(y=estimate__, ymin = lower__, ymax = upper__,x= effect1__, group = effect1__)) +
  facet_wrap(~Countryname, ncol = 3)

cond_notimeserieszi_mu_ddregime_only %>% 
  subset(eight_regions == "europe_west") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_errorbar(aes(y=estimate__, ymin = lower__, ymax = upper__,x= effect1__, group = effect1__)) +
  facet_wrap(~Countryname, ncol = 3)


```


# Regional country level plots zi
```{r condeffs_zi}
cond_notimeserieszi_zi_precip <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_zi$precip, ., by = "ISO")

cond_notimeserieszi_zi_rugged <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_zi$rugged, ., by = "ISO")

cond_notimeserieszi_zi_gdppc <- aei_nocrop_samp165aa_5yr %>% 
 dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_zi$gdppc, ., by = "ISO")

cond_notimeserieszi_zi_popdens <- aei_nocrop_samp165aa_5yr %>% 
 dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_zi$popdens, ., by = "ISO")

cond_notimeserieszi_zi_ddregime <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_zi$DD.regime, ., by = "ISO")

cond_notimeserieszi_zi_dist <- aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname)) %>% 
  left_join(cond_notimeserieszi_zi$dist, ., by = "ISO")
```


```{r condeffs_zi_plots_precip}

cond_notimeserieszi_zi_precip %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_precip %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_precip %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_precip %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_precip %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_precip %>% 
  subset(eight_regions == "africa_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_precip %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_precip %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```

```{r condeffs_zi_plots_rugged}

cond_notimeserieszi_zi_rugged %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_rugged %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_rugged %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_rugged %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_rugged %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_rugged %>% 
  subset(eight_regions == "africa_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_rugged %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_rugged %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```

```{r condeffs_zi_plots_gdppc}

cond_notimeserieszi_zi_gdppc %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_gdppc %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_gdppc %>% 
  subset(eight_regions == "america_north") %>% 
 ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_gdppc %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_gdppc %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_gdppc %>% 
  subset(eight_regions == "africa_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_gdppc %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_gdppc %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```

```{r condeffs_zi_plots_popdens}

cond_notimeserieszi_zi_popdens %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_popdens %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_popdens %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_popdens %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_popdens %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_popdens %>% 
  subset(eight_regions == "africa_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_popdens %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_popdens %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```

```{r condeffs_zi_plots_ddregime}

cond_notimeserieszi_zi_ddregime %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_ddregime %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_ddregime %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_ddregime %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_ddregime %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_ddregime %>% 
  subset(eight_regions == "africa_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_ddregime %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_ddregime %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```


```{r condeffs_zi_plots_dist}

cond_notimeserieszi_zi_dist %>% 
  subset(eight_regions == "asia_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_dist %>% 
  subset(eight_regions == "east_asia_pacific") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_dist %>% 
  subset(eight_regions == "america_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_dist %>% 
  subset(eight_regions == "america_south") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_dist %>% 
  subset(eight_regions == "africa_sub_saharan") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_dist %>% 
  subset(eight_regions == "africa_north") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_dist %>% 
  subset(eight_regions == "europe_east") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")

cond_notimeserieszi_zi_dist %>% 
  subset(eight_regions == "europe_west") %>% 
  ggplot(aes(x=effect1__, y=estimate__)) +
  geom_ribbon(aes(ymin = lower__, ymax = upper__,x= effect1__), alpha = 0.3) + 
  geom_line() +
  facet_wrap(~Countryname, ncol = 3, scales = "free_y")


```





```{r expected_mu_mu}

### New data give the old data and model. Does it predict back reasonable values?
# Solid line is the mean and the dashed is the 50% uncertainity interval.

Countrynames <- 
  aei_nocrop_samp165aa_5yr %>% 
  dplyr::select(ISO, eight_regions, Countryname) %>% 
  mutate(eight_regions = as.factor(eight_regions), 
         Countryname = as.factor(Countryname))


#posterior draws to construct mu


  composite_reg %>%
  spread_draws(b_Intercept, r_eight_regions[eight_regions,]) %>%
  # add the grand mean to the group-specific deviations
  mutate(mu = b_Intercept + r_eight_regions) %>%
  mutate(mu = plogis(mu)) %>%
  ungroup() %>% 
  ggplot(aes(x = mu, y = reorder(eight_regions, mu))) +
  geom_vline(xintercept = plogis(fixef(composite_reg)[1, 1]), color = "#839496", size = 1) +
  geom_vline(xintercept = plogis(fixef(composite_reg)[1, 3:4]), color = "#839496", linetype = 2) +
  geom_halfeyeh(.width = .5, size = 2/3, fill = "#859900") +
  xlim(0,0.10) 

  
  
composite_reg %>%
    spread_draws(b_zi_Intercept, r_eight_regions__zi[eight_regions,]) %>%
    # add the grand mean to the group-specific deviations
    mutate(zi = b_zi_Intercept + r_eight_regions__zi) %>%
    dplyr::mutate(zi = plogis(zi)) %>% 
    ungroup() %>% 
    ggplot(aes(x = zi, y = reorder(eight_regions, zi))) +
    geom_vline(xintercept = plogis(fixef(composite_reg)[13, 1]), color = "#839496", size = 1) +
    geom_vline(xintercept = plogis(fixef(composite_reg)[13, 3:4]), color = "#839496", linetype = 2) +
    geom_halfeyeh(.width = .5, size = 2/3, fill = "#859900")   
  
  
ggsave(mus, file = "/Volumes/RachelExternal2/Thesis/BayesMultilevelMods/figure/longplot.png", height = 20, units = "in")


```

```{r expected_mu_zi}


#posterior draws to construct zi
`165aa_5yronlyISO_notimeserieszi` %>%
  spread_draws(b_zi_Intercept, r_ISO__zi[ISO,]) %>%
  # add the grand mean to the group-specific deviations
  mutate(zi = b_zi_Intercept + r_ISO__zi) %>%
  mutate(zi = exp(zi)) %>% 
  ungroup() %>%
  
  
  # plot
  ggplot(aes(x = zi, y = reorder(ISO, zi))) +
  geom_vline(xintercept = exp(fixef(`165aa_5yronlyISO_notimeserieszi`)[13, 1]), color = "#839496", size = 1) +
  geom_vline(xintercept = exp(fixef(`165aa_5yronlyISO_notimeserieszi`)[13, 3:4]), color = "#839496", linetype = 2) +
  geom_halfeyeh(.width = .5, size = 2/3, fill = "#859900") +
  xlim(0,1) 
```

```{r}
#posterior draws to construct zi
coef %>% 
  # plot
  ggplot(aes(x = zi, y = reorder(ISO, zi))) +
  geom_vline(xintercept = exp(fixef(`165aa_5yronlyISO_notimeserieszi`)[13, 1]), color = "#839496", size = 1) +
  geom_vline(xintercept = exp(fixef(`165aa_5yronlyISO_notimeserieszi`)[13, 3:4]), color = "#839496", linetype = 2) +
  geom_halfeyeh(.width = .5, size = 2/3, fill = "#859900") +
  xlim(0,1) 
```

