
```{r}
library(ggmap)
library(raster)
library(ggplot2)
```


```{r cropland_vs_irrexpansion}
aei <- read.csv("/Volumes/RachelExternal2/Thesis/Data_and_Plots/aei_full.csv")
aei_nocrop <- read.csv("/Volumes/RachelExternal2/Thesis/Data_and_Plots/aei_nocrop.csv")
aei_sample <- read.csv("/Volumes/RachelExternal2/Thesis/Data_and_Plots/aei_nocrop_samp165aa_5yr.csv")
```

#
```{r}
iFol="/Volumes/RachelExternal2/Thesis/Thesis/Original_Grid_Data_Scripts/data/"
oFol="/Volumes/RachelExternal2/Thesis/Thesis/Plots/"
load(file=paste0(iFol,"data.RData"))

irrfrac <- as.data.frame(irrFrac)
cellarea <- as.data.frame(cellarea)

irrfrac <- irrfrac * t(cellarea)

years <- seq(1901, 2005, by = 1)

colsum <- colSums(irrfrac)
colsum <- as.data.frame(colsum*1e-6)
colsum$years <- years
colnames(colsum) <- c("Irrigation Fraction", "Year")

colsum <- colsum[-1,]

write.csv(colsum, file = "/Volumes/RachelExternal2/Thesis/Master_Thesis/data/irrcolsums.csv")


ggplot(data = colsum) + 
  geom_line(aes(y =`Irrigation Fraction`, x = Year), color = "green") +
  ylab(expression("Global Irrigated Area in"~km^2)) + 
  coord_cartesian(xlim = c(1901, 2005)) + 
  theme_minimal() 


```




# Study Area


```{r globalstudyarea}
world <- map_data("world") 
(ggplot(aes(x=lon,y=lat,fill=eight_regions),data=aei) + geom_tile())+geom_polygon(data=world,aes(x=long, y=lat, group=group), colour="black", fill="white", alpha=0) + 
  theme_minimal()+
  theme(
  legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
    axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()
  )

ggsave(file = "/Volumes/RachelExternal2/Thesis/plotsforpres/fullstudyarea.png", dpi = 500, width = 12, height =7)



```


```{r actualstudyarea}


(ggplot(aes(x=lon,y=lat,fill=eight_regions),data=aei_nocrop) + geom_tile())+geom_polygon(data=world,aes(x=long, y=lat, group=group), colour="black", fill="white", alpha=0) + 
  theme_minimal() +
  theme(
  legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
    axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()
  )

ggsave(file = "/Volumes/RachelExternal2/Thesis/plotsforpres/actualstudyarea.png", dpi = 500, width = 12, height =7)




```


```{r sampled_study_area}
(ggplot(aes(x=lon,y=lat,fill=eight_regions),data=aei_sample) + geom_tile())+geom_polygon(data=world,aes(x=long, y=lat, group=group), colour="black", fill="white", alpha=0) + 
  theme_minimal() +
  theme(
  legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
    axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()
  )

ggsave(file = "/Volumes/RachelExternal2/Thesis/plotsforpres/sampledstudyarea.png", dpi = 500, width = 12, height =7)

```


# Response Histogram

```{r irrfrachist}

  ggplot(data = aei_nocrop, aes(x=irrfrac)) +
  geom_histogram(bins = 100) +
  theme_minimal() + 
  xlab("Irrigation Fraction (% irrigated area per grid cell)") +
  theme(legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

ggsave(file = "/Volumes/RachelExternal2/Thesis/plotsforpres/irrfrachist.png", height = 4, width = 4)

```


# Variance in mu

```{r}
centered <-function(y) {
  x<-y[!is.na(y)]
  x<-(x - mean(x)) / (sd(x))
  y[!is.na(y)]<-x
  return(y)
}

aei_nocrop_samp165aa_5yr <- aei_nocrop_samp165aa_5yr[,-1]
aei_nocrop_samp165aa_5yr <-
  aei_nocrop_samp165aa_5yr %>% 
  mutate(across(c(13:20), centered)) %>% 
  mutate(across(c(1:3,6,7,21,22), as.factor)) 


#This works - this is predicted - plots varying intercepts of an intercept only model
bound <- 
  aei_nocrop_samp165aa_5yr %>%
  data_grid(ISO) %>%
  add_epred_draws(`165aa_5yronlyISO_uncondmeans`, dpar = "mu") %>%
  group_by(ISO) %>%
  mutate(medperclass = median(mu))%>%
  ungroup() 

aei_nocrop_samp165aa_5yr %>% 
  select(Countryname, ISO, eight_regions) %>% 
  mutate(Countryname = gsub("_", " ",.$Countryname)) %>% 
  unique() %>% 
  left_join(bound, ., by = "ISO") %>%
  ggplot(aes(x = mu, y = reorder(as.factor(Countryname), medperclass), color = eight_regions)) +
  stat_pointinterval(.width = c(.66, .95)) + 
  xlab(expression(paste("Proportion of irrigaiton per cell (", mu,")"))) +
  ylab("Country") +
  theme_minimal() +
  coord_flip() +
  ggtitle(expression(paste("Varation within and between countries for ", mu," parameter"))) +   
  labs(color = "Region") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size=rel(0.5)))

ggsave(last_plot(), filename = "/Volumes/RachelExternal2/Thesis/Thesis/final/plots/muinterceptmodepred.png", width = 12)
```

# Variance in zi

```{r}
#This works - this is predicted - plots varying intercepts of an intercept only model
zivar <- 
  aei_nocrop_samp165aa_5yr %>%
  data_grid(ISO) %>%
  add_epred_draws(`165aa_5yronlyISO_uncondmeans`, dpar = "zi") %>%
  group_by(ISO) %>%
  mutate(medperclass = median(zi))%>%
  ungroup() 

aei_nocrop_samp165aa_5yr %>% 
  select(Countryname, ISO, eight_regions) %>% 
  mutate(Countryname = gsub("_", " ",.$Countryname)) %>% 
  unique() %>% 
  left_join(zivar, ., by = "ISO") %>%
  ggplot(aes(x = zi, y = reorder(as.factor(Countryname), medperclass), color = eight_regions)) +
  stat_pointinterval(.width = c(.66, .95)) + 
  xlab(expression(paste("Proportion 0 vs. non-zero cells (", rho,")"))) +
  ylab("Country") +
  theme_minimal() +
  coord_flip() +
  ggtitle(expression(paste("Varation within and between countries for ", rho," parameter"))) +   
  labs(color = "Region") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size=rel(0.5)))

ggsave(last_plot(), filename = "/Volumes/RachelExternal2/Thesis/Thesis/final/plots/ziinterceptmodepred.png", width = 12)
```

#Variance in mu and zi aggregated to regional level
```{r}
#This works - this is predicted - plots varying intercepts of an intercept only model
zivar_reg <- 
  aei_nocrop_samp165aa_5yr %>%
  data_grid(ISO) %>%
  add_epred_draws(`165aa_5yronlyISO_uncondmeans`, dpar = c("zi", "mu")) 

aei_nocrop_samp165aa_5yr %>% 
  select(Countryname, ISO, eight_regions) %>% 
  mutate(Countryname = gsub("_", " ",.$Countryname)) %>% 
  unique() %>% 
  left_join(zivar_reg, ., by = "ISO") %>%
  group_by(eight_regions) %>%
  mutate(medperclass = median(zi))%>%
  ungroup() %>%
  ggplot(aes(x = zi, y = reorder(as.factor(eight_regions), medperclass), color = eight_regions)) +
  stat_pointinterval(.width = c(.66, .95)) + 
  xlab(expression(paste("Proportion 0 vs. non-zero cells (", zi,")"))) +
  ylab("Country") +
  theme_minimal() +
  coord_flip() +
  ggtitle(expression(paste("Varation within and between countries for ", zi," parameter"))) +   
  labs(color = "Region") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))+
  theme(legend.position = "none")

ggsave(last_plot(), filename = "/Volumes/RachelExternal2/Thesis/Thesis/final/plots/zi_intercept_modepred_eightres.png", width = 12)

aei_nocrop_samp165aa_5yr %>% 
  select(Countryname, ISO, eight_regions) %>% 
  mutate(Countryname = gsub("_", " ",.$Countryname)) %>% 
  unique() %>% 
  left_join(zivar_reg, ., by = "ISO") %>%
  group_by(eight_regions) %>%
  mutate(medperclass = median(mu))%>%
  ungroup() %>%
  ggplot(aes(x = mu, y = reorder(as.factor(eight_regions), medperclass), color = eight_regions)) +
  stat_pointinterval(.width = c(.66, .95)) + 
  xlab(expression(paste("Irrigation Fraction per Cell (", mu,")"))) +
  ylab("Country") +
  theme_minimal() +
  coord_flip() +
  ggtitle(expression(paste("Varation within and between countries for ", mu," parameter"))) +   
  labs(color = "Region") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))+
  theme(legend.position = "none")

ggsave(last_plot(), filename = "/Volumes/RachelExternal2/Thesis/Thesis/final/plots/mu_intercept_modepred_eightres.png", width = 12)

```




#bubble plot attempt
```{r}
library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(viridis)

bub <- 
  aei_nocrop_samp165aa_5yr %>%
  data_grid(ISO) %>%
  add_epred_draws(`165aa_5yronlyISO_uncondmeans`, dpar = c("mu", "zi")) 

# Most basic bubble plot
aei_nocrop_samp165aa_5yr %>% 
  select(Countryname, ISO, eight_regions) %>% 
  mutate(Countryname = gsub("_", " ",.$Countryname)) %>% 
  unique() %>% 
  left_join(bub, ., by = "ISO")  %>%
  group_by(eight_regions) %>% 
  mutate(medmu = median(mu),
            medzi = median(zi)) %>% 
  arrange(desc(medzi)) %>%
  ggplot(aes(x=medzi, y=medmu, fill=eight_regions)) +
    geom_point(shape=21, size = 5) +
  geom_errorbar(aes(ymin = min(mu),ymax = max(mu))) + 
    geom_errorbar(aes(xmin = min(zi),ymax = max(zi))) +
    theme_minimal()  +
    ylab("Irrigation Fraction per Irrigated Cell") +
    xlab("Proportion of 0 cells") 
```





# Uncond growth by region
```{r}


bound2 <- 
  aei_nocrop_samp165aa_5yr %>%
  data_grid(ISO, yearcount) %>%
  add_epred_draws(`165aa_5yronlyISO_uncondgrowth`, dpar = c("mu", "zi")) 

bound2 <-
  aei_nocrop_samp165aa_5yr %>% 
  select(ISO, eight_regions) %>% 
  unique() %>% 
  left_join(bound2, ., by = c("ISO"))

bound2 %>% 
  ggplot(aes(x = yearcount, y = mu, group = eight_regions, color = eight_regions))+
  stat_lineribbon(.width = c(0.66)) +
  theme_minimal() +
  facet_wrap(~eight_regions)+
  ylab("Irrigation Fraction per Irrigated Cell")+
  xlab("Yearcount (1960 = 0, 2005 = 45)") +
  ggtitle("Time series progression by region") +
  theme(legend.position = "none")

ggsave("/Volumes/RachelExternal2/Thesis/Thesis/final/plots/mu_timeseriesprogress.png")
```


```{r}
bound3 <- 
  aei_nocrop_samp165aa_5yr %>%
  data_grid(ISO, yearcount) %>%
  add_epred_draws(`165aa_5yronlyISO_uncondgrowth`, dpar = "zi") %>%
  group_by(ISO, yearcount) %>%
  summarise(meanperclass = mean(zi))

aei_nocrop_samp165aa_5yr %>% 
  select(ISO, eight_regions) %>% 
  unique() %>% 
  left_join(bound3, ., by = "ISO") %>%
  ggplot(aes(x = yearcount, y = meanperclass, color = ISO, group = ISO)) +
  geom_line() +
  theme(legend.position = "none") +
  facet_wrap(~eight_regions) 
```


#General Conditional Effects

```{r}
condeff_zi <- conditional_effects(`165aa_5yronlyISO_notimeserieszi`, dpar = "zi", plot = FALSE)
condeff_mu <- conditional_effects(`165aa_5yronlyISO_notimeserieszi`, dpar = "mu", plot = FALSE)

```


## zi

```{r}
rug <-
  ggplot(data = condeff_zi$rugged) + 
  geom_ribbon(aes(x=rugged, ymin=lower__, ymax = upper__), alpha = 0.4)+
  geom_line(aes(x=rugged, y=estimate__)) + 
  theme_minimal() +
  ylab(expression(paste("Proportion of non irrigated cells (", rho,")"))) +
  xlab("Standardized ruggedness index")
  
```


```{r}
dist <- ggplot(data = condeff_zi$dist) + 
  geom_ribbon(aes(x=dist, ymin=lower__, ymax = upper__), alpha = 0.4)+
  geom_line(aes(x=dist, y=estimate__)) + 
  theme_minimal() +
  ylab(expression(paste("Proportion of non irrigated cells (", rho,")"))) +
  xlab("Standardized distance to the next irrigated cell")
```
```{r}
gdppc <- 
  ggplot(data = condeff_zi$gdppc) + 
  geom_ribbon(aes(x=gdppc, ymin=lower__, ymax = upper__), alpha = 0.4)+
  geom_line(aes(x=gdppc, y=estimate__)) + 
  theme_minimal() +
  ylab(expression(paste("Proportion of non irrigated cells (", rho,")"))) +
  xlab("Standardized GDP per capita")
```

```{r}
ggplot(data = condeff_zi$precip) + 
  geom_ribbon(aes(x=precip, ymin=lower__, ymax = upper__), alpha = 0.4)+
  geom_line(aes(x=precip, y=estimate__)) + 
  theme_minimal() +
  ylab(expression(paste("Proportion of non irrigated cells (", rho,")"))) +
  xlab("Standardized Precipitation")
```



## mu

```{r}
ggplot(data = condeff_mu$yearcount) + 
  geom_ribbon(aes(x=yearcount, ymin=lower__, ymax = upper__), alpha = 0.4)+
  geom_line(aes(x=yearcount, y=estimate__)) + 
  theme_minimal() +
  ylab(expression(paste("Irrigation Fracion per Irrigated Cell (", mu,")"))) +
  xlab("Yearcount")+
  ggtitle("Global effect of time")

ggsave(last_plot(), filename = "/Volumes/RachelExternal2/Thesis/Thesis/final/plots/mu_yearcount.png")

```

```{r}
ggplot(data = condeff_mu$`yearcount:precip`) + 
  geom_ribbon(aes(x=yearcount, ymin=lower__, ymax = upper__, group = effect2__, fill = effect2__), alpha = 0.4)+
  geom_line(aes(x=yearcount, y=estimate__, group = effect2__, color = effect2__ )) + 
  theme_minimal() +
  ylab(expression(paste("Irrigation Fracion per Irrigated Cell (", mu,")"))) +
  xlab("Yearcount")+
  theme(legend.position = "none")+ 
  ggtitle("Precipitation over time")

ggsave(last_plot(), filename = "/Volumes/RachelExternal2/Thesis/Thesis/final/plots/mu_yearcount:precip.png")
```
```{r}
ggplot(data = condeff_mu$`yearcount:rugged`) + 
  geom_ribbon(aes(x=yearcount, ymin=lower__, ymax = upper__, group = effect2__, fill = effect2__), alpha = 0.4)+
  geom_line(aes(x=yearcount, y=estimate__, group = effect2__, color = effect2__ )) + 
  theme_minimal() +
  ylab(expression(paste("Irrigation Fracion per Irrigated Cell (", mu,")"))) +
  xlab("Yearcount")+
  theme(legend.position = "none")+ 
  ggtitle("Ruggedness over time")

ggsave(last_plot(), filename = "/Volumes/RachelExternal2/Thesis/Thesis/final/plots/mu_yearcount:ruggedness.png")
```
```{r}
ggplot(data = condeff_mu$`yearcount:gdppc`) + 
  geom_ribbon(aes(x=yearcount, ymin=lower__, ymax = upper__, group = effect2__, fill = effect2__), alpha = 0.4)+
  geom_line(aes(x=yearcount, y=estimate__, group = effect2__, color = effect2__ )) + 
  theme_minimal() +
  ylab(expression(paste("Irrigation Fracion per Irrigated Cell (", mu,")"))) +
  xlab("Yearcount")+
  theme(legend.position = "none")+ 
  ggtitle("Income over time")

ggsave(last_plot(), filename = "/Volumes/RachelExternal2/Thesis/Thesis/final/plots/mu_yearcount:income.png")
```
```{r}
ggplot(data = condeff_mu$`yearcount:popdens`) + 
  geom_ribbon(aes(x=yearcount, ymin=lower__, ymax = upper__, group = effect2__, fill = effect2__), alpha = 0.4)+
  geom_line(aes(x=yearcount, y=estimate__, group = effect2__, color = effect2__ )) + 
  theme_minimal() +
  ylab(expression(paste("Irrigation Fracion per Irrigated Cell (", mu,")"))) +
  xlab("Yearcount")+
  theme(legend.position = "none")+ 
  ggtitle("Population density over time")

ggsave(last_plot(), filename = "/Volumes/RachelExternal2/Thesis/Thesis/final/plots/mu_yearcount:popdens.png")
```
```{r}
ggplot(data = condeff_mu$`yearcount:DD.regime`) + 
  geom_ribbon(aes(x=yearcount, ymin=lower__, ymax = upper__, group = effect2__, fill = effect2__), alpha = 0.4)+
  geom_line(aes(x=yearcount, y=estimate__, group = effect2__, color = effect2__ )) + 
  theme_minimal() +
  ylab(expression(paste("Irrigation Fracion per Irrigated Cell (", mu,")"))) +
  xlab("Yearcount")+
  theme(legend.position = "none")+ 
  ggtitle("Democratic regime over time")+
  facet_wrap(~effect2__)

ggsave(last_plot(), filename = "/Volumes/RachelExternal2/Thesis/Thesis/final/plots/mu_yearcount:demo.png")
```


```{r}
cond <- make_conditions(aei_nocrop_samp165aa_5yr, vars = c("ISO"))
effectszi <- conditional_effects(`165aa_5yronlyISO_notimeserieszi`, conditions = cond, re_formula = NULL, dpar = "zi")
```

```{r}
namerica <- aei_nocrop_samp165aa_5yr %>% subset(eight_regions == "america_north") %>% select(ISO) %>% unique()

namerica <- as.list(namerica)

namerica_plot <- yearcount %>% subset(., subset = ISO %in% c("USA",  "CAN",  "MEX",  "GTM",  "SLV",  "HND",  "NIC",  "CRI",  "PAN",  "CUB",  "HTI",  "DOM",  "TTO") )

namerica_plot %>% 
  ggplot(aes(x = yearcount, y=estimate__, group =ISO, color=ISO)) +
  geom_line() +
  geom_ribbon(aes(ymin = lower__, ymax = upper__), alpha = 0.1)
```

